version: '3.5'

services:
  loki:
    container_name: loki
    image: grafana/loki:master
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - grafana-loki
      - promtail-loki

  promtail:
    container_name: promtail  
    depends_on:
      - loki
    image:  grafana/promtail:2.7.4
    volumes:
      - ${PWD}/promtail/promtail.yaml:/etc/promtail/docker-config.yaml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/docker-config.yaml
    networks:
      - promtail-loki

  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    privileged: true
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg:/dev/kmsg
    networks:
      - prometheus-cadvisor

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.7.1
    ports:
      - "9090:9090"
    volumes:
      - ${PWD}/prometheus:/app.cfg
    networks:
      - world
      - prometheus-cadvisor
      - grafana-prometheus
    command: >-
      --config.file=/app.cfg/prometheus.yml --storage.tsdb.path=/prometheus --web.console.libraries=/usr/share/prometheus/console_libraries --web.console.templates=/usr/share/prometheus/consoles

  grafana:
    container_name: grafana
    depends_on:
      - loki
    image: grafana/grafana:6.0.0
    ports:
      - 3000:3000
    expose:
      - 3000
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: meetlab123
      GF_PATHS_PROVISIONING: '/app.cfg/provisioning'
      VIRTUAL_HOST: grafana.theboxlabs.com,grafana.quocnp.tech
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: grafana.theboxlabs.com,grafana.quocnp.tech
    volumes:
      - ${PWD}/grafana:/app.cfg
    networks:
      - world
      - grafana-loki
      - grafana-prometheus
      - proxy

networks:
  world:
  proxy:
    name: proxy
  promtail-loki:
    internal: true
  grafana-loki:
    internal: true
  grafana-prometheus:
    internal: true
  prometheus-cadvisor:
    internal: true
