name: deploy-antelope

on:
  push:
    tags:
        - 'atl-realease*' # db: dashboard
  workflow_dispatch:
jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Start Deployment
      uses: thebox-lab/docker-remote-deployment-action@v0.0.1-rc01
      with:
        remote_docker_host: ${{ secrets.DOCKER_HOST }}
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
        stack_file_name: docker/docker-compose-admin.yml
        args: -p meet-lab-atl up -d
  